In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vectorizer = CountVectorizer()
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [28]:
corpus = [
     'This is the first document.',
     'This is the second second document second.',
#      'And the third one.',
#      'Is this the first document?',
 ]
X = vectorizer.fit_transform(corpus)
X.toarray()
X
# X 对应每个单词在该句子中出现的次数

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [27]:
vectorizer.get_feature_names()

['document', 'first', 'is', 'second', 'the', 'this']

In [34]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),
                                     token_pattern=r'\b\w+\b', min_df=1)
analyze=bigram_vectorizer.build_analyzer()
analyze('Bi-grams are cool!')


['bi', 'grams', 'are', 'cool', 'bi grams', 'grams are', 'are cool']

In [32]:
X2=bigram_vectorizer.fit_transform(corpus)
bigram_vectorizer.get_feature_names()

['document',
 'document second',
 'first',
 'first document',
 'is',
 'is the',
 'second',
 'second document',
 'second second',
 'the',
 'the first',
 'the second',
 'this',
 'this is']

In [36]:
corpus

['This is the first document.', 'This is the second second document second.']

In [37]:
X2.toarray()

array([[1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 3, 1, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [40]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer=TfidfTransformer(smooth_idf=False)
transformer

TfidfTransformer(norm='l2', smooth_idf=False, sublinear_tf=False, use_idf=True)

In [42]:
counts = [[3, 0, 1],
           [2, 0, 0],
           [3, 0, 0],
           [4, 0, 0],
           [3, 2, 0],
           [3, 0, 2]]
tfidf=transformer.fit_transform(counts)
tfidf.toarray()

array([[0.81940995, 0.        , 0.57320793],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.47330339, 0.88089948, 0.        ],
       [0.58149261, 0.        , 0.81355169]])

In [43]:
transformer.idf_

array([1.        , 2.79175947, 2.09861229])